version: '3.8'

services:
  # La Base de Datos (PostgreSQL)
  db:
    image: postgres:15
    container_name: db-restaurante
    restart: always
    environment:
      POSTGRES_USER: user_restaurante
      POSTGRES_PASSWORD: password_123
      POSTGRES_DB: restaurante_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Tu aplicación NestJS (El Backend)
  backend:
    build: .
    container_name: nestjs-restaurante
    restart: always
    ports:
      - "3005:3000"
    environment:
      # Esta línea es la que hace la magia de conectar ambos servicios
      DATABASE_URL: "postgresql://user_restaurante:password_123@db:5432/restaurante_db?schema=public"
    depends_on:
      - db

volumes:
  postgres_data:
  
  